name: json-yaml-validate 
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test examples
        id: json-yaml-validate-v3
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true"
          base_dir: examples/
          json_schema: signals.json
